// resuma-routes-fingerprint: c3ed9297de896b4b
// Auto-generated by `resuma routes --generate`. Do not edit by hand.
use resuma::prelude::*;
use resuma::FlowPageRegistry;

pub struct PagesRegistry;

impl FlowPageRegistry for PagesRegistry {
fn routes(&self) -> &'static [(&'static str, &'static str)] {
&[
                    ("/", "index"),
                    ("/about", "about"),
                    ("/contact", "contact"),
                    ("/work", "work"),
                ]
}

fn layout_for(&self, pattern: &str) -> &'static [&'static str] {
match pattern {
                    "/" => &["/"],
                    "/about" => &["/"],
                    "/contact" => &["/"],
                    "/work" => &["/"],
                    _ => &[],
}
}

fn render(&self, module: &str, req: FlowRequest) -> Option<View> {
match module {
            "index" => Some(super::index::page(req)),
            "about" => Some(super::about::page(req)),
            "contact" => Some(super::contact::page(req)),
            "work" => Some(super::work::page(req)),
            _ => None,
}
}
}
